version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=car_rental
      - DB_SSL_MODE=disable
    depends_on:
      - postgres
    volumes:
      - .:/app
      - app-data:/app/bin
    networks:
      - car-rental-network

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=car_rental
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - car-rental-network

volumes:
  postgres-data:
  app-data:

networks:
  car-rental-network:
    driver: bridge 